### ISSUE TITLE
Using Piwik API with LoginHttpAuth

### ISSUE THREAD

**Issue by ford42prefect** [piwik/plugin-LoginHttpAuth#8]
When I call the Piwik API like
http://piwik.my-intranet-domain.de/?module=API&method=VisitsSummary.getVisits&idSite=2&period=day&date=yesterday&format=XML&segment=pageUrl=@850487&token_auth=68baf4ffffffffffffffffffffffc25e4
i am asked for a password.
The point is, i use a dummy user for this, and want to skip Authentication using token_auth like described in http://developer.piwik.org/guides/querying-the-reporting-api

**Comment by justnx** [comment]
Same here when using import_logs.py via api.

**Comment by diosmosis** [comment]
Should be fixed in 1.0.3.

**Comment by mattab** [comment]
:+1:

**Comment by ford42prefect** [comment]
Is there a way  to skip authentication in .htaccess for API-Calls through index.php?
The only way I found, was copying index.php to api.php and granting access to api.php like I do for piwik.php.
